apiVersion: v1
kind: PersistentVolume
metadata:
  name: fast-n-foodious-pv
spec:
  capacity:
    storage: 500Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: fast-n-foodious-storage
  hostPath:
     path: /tmp/lib/mysql
     type: DirectoryOrCreate